# Generated by Django 5.2 on 2025-05-06 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Юзернейм')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя канала')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.botuser', verbose_name='Пользователь бота')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creates_join_request', models.BooleanField(default=False, verbose_name='Запрос на добавление')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='is revoked')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя ссылки')),
                ('creator', models.CharField(blank=True, max_length=250, null=True, verbose_name='Создатель')),
                ('expire_date', models.CharField(blank=True, max_length=150, null=True, verbose_name='Время истечения')),
                ('member_limit', models.IntegerField(blank=True, null=True, verbose_name='Лимит подписок')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('pending_join_request_count', models.IntegerField(blank=True, null=True, verbose_name='pending_join_request_count')),
                ('telegram_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.telegramchat', verbose_name='Телеграм канал')),
            ],
            options={
                'verbose_name': 'Пригласительная ссылка',
                'verbose_name_plural': 'Пригласительные ссылки',
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Юзернейм')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('subscribed', models.BooleanField(default=False, verbose_name='Подписан')),
                ('datetime_subscribed', models.DateTimeField(blank=True, null=True, verbose_name='Время подписки')),
                ('datetime_unsubscribed', models.DateTimeField(blank=True, null=True, verbose_name='Время отписки')),
                ('invite_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.invitelink', verbose_name='Пригласительная ссылка')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
    ]
