# Generated by Django 5.2 on 2025-05-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramchat',
            name='bot_user',
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='chat_id',
            field=models.PositiveBigIntegerField(default=1, verbose_name='ID Канала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Username канала'),
        ),
    ]
