# Generated by Django 5.2 on 2025-05-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_remove_telegramchat_bot_user_telegramchat_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='chat_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID Канала'),
        ),
    ]
