# Generated by Django 5.2 on 2025-05-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_alter_telegramchat_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID Канала'),
        ),
    ]
