# Generated by Django 5.2 on 2025-05-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_alter_telegramchat_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='chat_id',
            field=models.BigIntegerField(default=1, verbose_name='ID Канала'),
            preserve_default=False,
        ),
    ]
