# Generated by Django 5.2 on 2025-05-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_telegramchat_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='public_link',
            field=models.BooleanField(default=False, verbose_name='Публичная ссылка'),
        ),
    ]
