# Generated by Django 5.2 on 2025-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_invitelink_public_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitelink',
            name='creator',
        ),
        migrations.AddField(
            model_name='invitelink',
            name='creator_full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Создатель name'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='creator_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Создатель id'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='creator_username',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Создатель username'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='Уведомление о подписках'),
        ),
    ]
