# Generated by Django 5.2 on 2025-05-10 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_remove_invitelink_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsubscriber',
            name='telegram_chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tgbot.telegramchat', verbose_name='Телеграм канал'),
            preserve_default=False,
        ),
    ]
