# Generated by Django 5.2 on 2025-05-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_telegramsubscriber_telegram_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID Telegram'),
        ),
    ]
